#!/bin/bash

VERB="$1"

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

if [[ -z $STOW_FOLDERS ]]; then
    cd $DOTFILES
    STOW_FOLDERS=$(ls -d */ | tr -d /)
fi

install() {
    pushd $DOTFILES
    for folder in $STOW_FOLDERS; do
        stow -D $folder
        stow $folder
    done
    popd
}

clean() {
    pushd $DOTFILES
    for folder in $STOW_FOLDERS; do
        echo "Removing $folder"
        stow -D $folder
    done
    popd
}

if [[ $VERB = "install" ]]; then
  echo "Installing dotfiles!" && install
elif [[ "$VERB" = "clean" ]]; then
  echo "Cleaning dotfiles!" && clean
else
  echo "ARGS must be 'install' or 'clean'"
fi
