#!/bin/sh
#================================================================================
#           _                        _ _
#       ___| |_ __  __ _ _ _ __ _  _| (_)_ _  ___
#      / -_) | '  \/ _` | '_/ _| || | | | ' \/ _ \
#      \___|_|_|_|_\__,_|_| \__|\_,_|_|_|_||_\___/
#     ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#     ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#     ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#     ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#     ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#     ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#
#================================================================================

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width             2
bspc config window_gap               0
bspc config top_padding              26

bspc config normal_border_color "#30302F"
bspc config active_border_color "#30302F"
bspc config focused_border_color "#AA67C6"
bspc config presel_feedback_color "#AA67C6"

bspc config split_ratio              0.5
bspc config history_aware_focus      true
bspc config focus_follows_pointers   false
bspc config pointer_follows_focus    false
bspc config click_to_focus           true
bspc config borderless_monocle       true
bspc config gapless_monocle          true

# https://www.reddit.com/r/bspwm/comments/e9u07i/how_to_spawn_new_windows_on_the_right/
bspc config automatic_scheme         longest_side
#bspc config automatic_scheme         shortest_side
bspc config initial_polarity         second_child
#bspc config initial_polarity         first_child

# move and resize windows with the mouse pointer
bspc config pointer_modifier         mod4
bspc config pointer_action1          move
bspc config pointer_action2          resize_side
bspc config pointer_action2          resize_corner

bspc rule -a Alacritty focus=on follow=on
bspc rule -a Screenkey manage=off
bspc rule -a mplayer2 state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a vlc desktop='^4' follow=on focus=on
bspc rule -a copyq state=floating follow=on focus=on
bspc rule -a feh state=floating follow=on

